DEBUG 2016-08-24 17:13:01,219: 	 Executing command: 'status'
DEBUG 2016-08-24 17:13:01,219: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-08-24 17:13:01,226: 	 Checking credentials
DEBUG 2016-08-24 17:13:01,226: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-08-24 17:13:01,226: 	 Getting proxy life time left
DEBUG 2016-08-24 17:13:01,329: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 86365

 error: 
 retcode : 0
DEBUG 2016-08-24 17:13:01,432: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 86364

 error: 
 retcode : 0
DEBUG 2016-08-24 17:13:01,432: 	 Proxy valid for 23:59:25 hours
ERROR 2016-08-24 17:13:01,433: 	 Cannot find .requestcache file in CRAB project directory /uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015
ERROR 2016-08-24 17:13:01,433: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015
DEBUG 2016-08-24 17:15:45,699: 	 Executing command: 'submit'
DEBUG 2016-08-24 17:15:45,700: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-08-24 17:15:45,714: 	 Checking credentials
DEBUG 2016-08-24 17:15:45,714: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-08-24 17:15:45,715: 	 Getting proxy life time left
DEBUG 2016-08-24 17:15:45,818: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 86201

 error: 
 retcode : 0
DEBUG 2016-08-24 17:15:45,921: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 86200

 error: 
 retcode : 0
DEBUG 2016-08-24 17:15:45,921: 	 Proxy valid for 23:56:41 hours
INFO 2016-08-24 17:15:45,921: 	 Will use CRAB configuration file crab.py
DEBUG 2016-08-24 17:15:45,922: 	 Loading CRAB configuration file.
DEBUG 2016-08-24 17:15:45,925: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-24 17:15:45,926: 	 Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015' already exists 
Please change the requestName in the config file
ERROR 2016-08-24 17:15:45,926: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015' already exists 
Please change the requestName in the config file
DEBUG 2016-08-24 17:43:30,158: 	 Executing command: 'submit'
DEBUG 2016-08-24 17:43:30,159: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-08-24 17:43:30,175: 	 Checking credentials
DEBUG 2016-08-24 17:43:30,176: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-08-24 17:43:30,176: 	 Getting proxy life time left
DEBUG 2016-08-24 17:43:30,279: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 84536

 error: 
 retcode : 0
DEBUG 2016-08-24 17:43:30,381: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 84535

 error: 
 retcode : 0
DEBUG 2016-08-24 17:43:30,382: 	 Proxy valid for 23:28:56 hours
INFO 2016-08-24 17:43:30,382: 	 Will use CRAB configuration file crab.py
DEBUG 2016-08-24 17:43:30,382: 	 Loading CRAB configuration file.
DEBUG 2016-08-24 17:43:30,494: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-24 17:43:30,494: 	 Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015' already exists 
Please change the requestName in the config file
ERROR 2016-08-24 17:43:30,494: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015' already exists 
Please change the requestName in the config file
DEBUG 2016-08-26 15:42:15,198: 	 Executing command: 'submit'
DEBUG 2016-08-26 15:42:15,199: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-08-26 15:42:15,204: 	 Checking credentials
DEBUG 2016-08-26 15:42:15,204: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-08-26 15:42:15,204: 	 Getting proxy life time left
DEBUG 2016-08-26 15:42:15,305: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 78917

 error: 
 retcode : 0
DEBUG 2016-08-26 15:42:15,407: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 78917

 error: 
 retcode : 0
DEBUG 2016-08-26 15:42:15,408: 	 Proxy valid for 21:55:17 hours
INFO 2016-08-26 15:42:15,408: 	 Will use CRAB configuration file crab.py
DEBUG 2016-08-26 15:42:15,408: 	 Loading CRAB configuration file.
DEBUG 2016-08-26 15:42:15,425: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-26 15:42:15,425: 	 Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015_test' already exists 
Please change the requestName in the config file
ERROR 2016-08-26 15:42:15,425: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015_test' already exists 
Please change the requestName in the config file
DEBUG 2016-08-26 17:39:59,043: 	 Executing command: 'submit'
DEBUG 2016-08-26 17:39:59,043: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-08-26 17:39:59,047: 	 Checking credentials
DEBUG 2016-08-26 17:39:59,047: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-08-26 17:39:59,047: 	 Getting proxy life time left
DEBUG 2016-08-26 17:39:59,149: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 71853

 error: 
 retcode : 0
DEBUG 2016-08-26 17:39:59,251: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 71853

 error: 
 retcode : 0
DEBUG 2016-08-26 17:39:59,251: 	 Proxy valid for 19:57:33 hours
INFO 2016-08-26 17:39:59,251: 	 Will use CRAB configuration file crab.py
DEBUG 2016-08-26 17:39:59,251: 	 Loading CRAB configuration file.
DEBUG 2016-08-26 17:39:59,268: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-26 17:39:59,268: 	 Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015_test' already exists 
Please change the requestName in the config file
ERROR 2016-08-26 17:39:59,268: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015_test' already exists 
Please change the requestName in the config file
DEBUG 2016-08-26 17:40:02,662: 	 Executing command: 'kill'
DEBUG 2016-08-26 17:40:02,662: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
ERROR 2016-08-26 17:40:02,663: 	 Error: Please indicate the CRAB project directory with --dir=<project-directory>.
ERROR 2016-08-26 17:40:02,663: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 62, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 562, in validateOptions
    raise ex
MissingOptionException: [91mError[0m: Please indicate the CRAB project directory with --dir=<project-directory>.
DEBUG 2016-08-26 17:40:24,685: 	 Executing command: 'kill'
DEBUG 2016-08-26 17:40:24,686: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
ERROR 2016-08-26 17:40:24,687: 	 Error: =crab_projects/crab_DYToLLNtuplerRunIISpring2015_test/ is not a valid CRAB project directory.
ERROR 2016-08-26 17:40:24,687: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 62, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: =crab_projects/crab_DYToLLNtuplerRunIISpring2015_test/ is not a valid CRAB project directory.
DEBUG 2016-08-26 17:40:32,195: 	 Executing command: 'kill'
DEBUG 2016-08-26 17:40:32,195: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
ERROR 2016-08-26 17:40:32,196: 	 Error: =crab_projects/crab_DYToLLNtuplerRunIISpring2015_test/ is not a valid CRAB project directory.
ERROR 2016-08-26 17:40:32,196: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 257, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/kill.py", line 62, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 566, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: =crab_projects/crab_DYToLLNtuplerRunIISpring2015_test/ is not a valid CRAB project directory.
DEBUG 2016-08-26 17:44:08,778: 	 Executing command: 'submit'
DEBUG 2016-08-26 17:44:08,778: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-08-26 17:44:08,783: 	 Checking credentials
DEBUG 2016-08-26 17:44:08,783: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-08-26 17:44:08,783: 	 Getting proxy life time left
DEBUG 2016-08-26 17:44:08,884: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 71604

 error: 
 retcode : 0
DEBUG 2016-08-26 17:44:08,986: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 71604

 error: 
 retcode : 0
DEBUG 2016-08-26 17:44:08,986: 	 Proxy valid for 19:53:24 hours
INFO 2016-08-26 17:44:08,987: 	 Will use CRAB configuration file crab.py
DEBUG 2016-08-26 17:44:08,987: 	 Loading CRAB configuration file.
DEBUG 2016-08-26 17:44:08,989: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-08-26 17:44:08,990: 	 Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015_test' already exists 
Please change the requestName in the config file
ERROR 2016-08-26 17:44:08,990: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_DYToLLNtuplerRunIISpring2015_test' already exists 
Please change the requestName in the config file
DEBUG 2016-08-30 18:51:31,680: 	 Executing command: 'kill'
DEBUG 2016-08-30 18:51:31,681: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-08-30 18:51:31,687: 	 Checking credentials
DEBUG 2016-08-30 18:51:31,687: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-08-30 18:51:31,687: 	 Getting proxy life time left
DEBUG 2016-08-30 18:51:31,789: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 60049

 error: 
 retcode : 0
DEBUG 2016-08-30 18:51:31,892: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 60049

 error: 
 retcode : 0
DEBUG 2016-08-30 18:51:31,892: 	 Proxy valid for 16:40:49 hours
ERROR 2016-08-30 18:51:31,893: 	 Cannot find .requestcache file in CRAB project directory /uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_WJToLLNtuplerRunII2015_v1
ERROR 2016-08-30 18:51:31,893: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_WJToLLNtuplerRunII2015_v1
DEBUG 2016-08-30 18:57:48,049: 	 Executing command: 'status'
DEBUG 2016-08-30 18:57:48,050: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-08-30 18:57:48,058: 	 Checking credentials
DEBUG 2016-08-30 18:57:48,058: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-08-30 18:57:48,058: 	 Getting proxy life time left
DEBUG 2016-08-30 18:57:48,161: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 59672

 error: 
 retcode : 0
DEBUG 2016-08-30 18:57:48,263: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 59672

 error: 
 retcode : 0
DEBUG 2016-08-30 18:57:48,264: 	 Proxy valid for 16:34:32 hours
ERROR 2016-08-30 18:57:48,264: 	 Cannot find .requestcache file in CRAB project directory /uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_WJToLLNtuplerRunII2015_v1
ERROR 2016-08-30 18:57:48,264: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 321, in __init__
    self.loadLocalCache(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 450, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_WJToLLNtuplerRunII2015_v1
DEBUG 2016-08-30 18:58:16,938: 	 Executing command: 'submit'
DEBUG 2016-08-30 18:58:16,939: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-08-30 18:58:16,945: 	 Checking credentials
DEBUG 2016-08-30 18:58:16,945: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-08-30 18:58:16,945: 	 Getting proxy life time left
DEBUG 2016-08-30 18:58:17,047: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 59644

 error: 
 retcode : 0
DEBUG 2016-08-30 18:58:17,150: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 59643

 error: 
 retcode : 0
DEBUG 2016-08-30 18:58:17,151: 	 Proxy valid for 16:34:04 hours
INFO 2016-08-30 18:58:17,151: 	 Will use CRAB configuration file crab.py
DEBUG 2016-08-30 18:58:17,151: 	 Loading CRAB configuration file.
ERROR 2016-08-30 18:58:17,167: 	 Error while loading CRAB configuration:
invalid syntax (crab.py, line 38)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2016-08-30 18:58:17,167: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
invalid syntax (crab.py, line 38)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2016-09-08 18:12:54,760: 	 Executing command: 'submit'
DEBUG 2016-09-08 18:12:54,765: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-08 18:12:54,773: 	 Checking credentials
DEBUG 2016-09-08 18:12:54,773: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-09-08 18:12:54,773: 	 Getting proxy life time left
DEBUG 2016-09-08 18:12:54,875: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2016-09-08 18:12:54,875: 	 Proxy valid for 00:00:00 hours
DEBUG 2016-09-08 18:12:54,875: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-09-08 18:14:38,886: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 0
DEBUG 2016-09-08 18:14:38,997: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 86400

 error: 
 retcode : 0
DEBUG 2016-09-08 18:14:39,099: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 86399

 error: 
 retcode : 0
DEBUG 2016-09-08 18:14:39,201: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u50707 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL
/cms/uscms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
DEBUG 2016-09-08 18:14:39,201: 	 Proxy created.
INFO 2016-09-08 18:14:39,201: 	 Will use CRAB configuration file crab.py
DEBUG 2016-09-08 18:14:39,201: 	 Loading CRAB configuration file.
ERROR 2016-09-08 18:14:39,244: 	 Error while loading CRAB configuration:
invalid syntax (crab.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2016-09-08 18:14:39,244: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
invalid syntax (crab.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2016-09-08 18:14:53,518: 	 Executing command: 'submit'
DEBUG 2016-09-08 18:14:53,518: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-08 18:14:53,522: 	 Checking credentials
DEBUG 2016-09-08 18:14:53,522: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-09-08 18:14:53,522: 	 Getting proxy life time left
DEBUG 2016-09-08 18:14:53,624: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 86385

 error: 
 retcode : 0
DEBUG 2016-09-08 18:14:53,726: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 86385

 error: 
 retcode : 0
DEBUG 2016-09-08 18:14:53,726: 	 Proxy valid for 23:59:45 hours
INFO 2016-09-08 18:14:53,726: 	 Will use CRAB configuration file crab.py
DEBUG 2016-09-08 18:14:53,727: 	 Loading CRAB configuration file.
ERROR 2016-09-08 18:14:53,728: 	 Error while loading CRAB configuration:
invalid syntax (crab.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2016-09-08 18:14:53,728: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
invalid syntax (crab.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2016-09-08 18:15:55,741: 	 Executing command: 'submit'
DEBUG 2016-09-08 18:15:55,741: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-08 18:15:55,745: 	 Checking credentials
DEBUG 2016-09-08 18:15:55,745: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-09-08 18:15:55,745: 	 Getting proxy life time left
DEBUG 2016-09-08 18:15:55,847: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 86323

 error: 
 retcode : 0
DEBUG 2016-09-08 18:15:55,949: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 86323

 error: 
 retcode : 0
DEBUG 2016-09-08 18:15:55,949: 	 Proxy valid for 23:58:43 hours
INFO 2016-09-08 18:15:55,950: 	 Will use CRAB configuration file crab.py
DEBUG 2016-09-08 18:15:55,950: 	 Loading CRAB configuration file.
ERROR 2016-09-08 18:15:55,952: 	 Error while loading CRAB configuration:
invalid syntax (crab.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2016-09-08 18:15:55,952: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
invalid syntax (crab.py, line 16)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2016-09-13 01:38:52,506: 	 Executing command: 'submit'
DEBUG 2016-09-13 01:38:52,515: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-13 01:38:52,532: 	 Checking credentials
DEBUG 2016-09-13 01:38:52,532: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-09-13 01:38:52,532: 	 Getting proxy life time left
DEBUG 2016-09-13 01:38:52,635: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 38597

 error: 
 retcode : 0
DEBUG 2016-09-13 01:38:52,737: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 
 error: 
 retcode : 1
DEBUG 2016-09-13 01:38:52,738: 	 Proxy valid for 00:00:00 hours
DEBUG 2016-09-13 01:38:52,738: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
ERROR 2016-09-13 01:58:52,799: 	 Timeout in voms-proxy-init -voms cms:/cms -valid 24:00 -rfc execution.
DEBUG 2016-09-13 01:58:52,905: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 37397

 error: 
 retcode : 0
DEBUG 2016-09-13 01:58:53,008: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 
 error: 
 retcode : 1
DEBUG 2016-09-13 01:58:53,111: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u50707 voms-proxy-info -fqan
 output : 
 error: 
 retcode : 1
ERROR 2016-09-13 01:58:53,111: 	 Problems creating proxy.
ERROR 2016-09-13 01:58:53,111: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-09-13 13:38:37,155: 	 Executing command: 'submit'
DEBUG 2016-09-13 13:38:37,156: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-13 13:38:37,164: 	 Checking credentials
DEBUG 2016-09-13 13:38:37,164: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-09-13 13:38:37,164: 	 Getting proxy life time left
DEBUG 2016-09-13 13:38:37,267: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 4738

 error: 
 retcode : 0
DEBUG 2016-09-13 13:38:37,370: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 4738

 error: 
 retcode : 0
DEBUG 2016-09-13 13:38:37,370: 	 Proxy valid for 01:18:58 hours
INFO 2016-09-13 13:38:37,370: 	 Will use CRAB configuration file crab.py
DEBUG 2016-09-13 13:38:37,371: 	 Loading CRAB configuration file.
DEBUG 2016-09-13 13:38:37,374: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-09-13 13:38:37,375: 	 Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_WHToZZTo4LNtuplerRunII2015_v1' already exists 
Please change the requestName in the config file
ERROR 2016-09-13 13:38:37,375: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_WHToZZTo4LNtuplerRunII2015_v1' already exists 
Please change the requestName in the config file
DEBUG 2016-09-13 13:48:18,774: 	 Executing command: 'submit'
DEBUG 2016-09-13 13:48:18,775: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-13 13:48:18,783: 	 Checking credentials
DEBUG 2016-09-13 13:48:18,783: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-09-13 13:48:18,783: 	 Getting proxy life time left
DEBUG 2016-09-13 13:48:18,886: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 4157

 error: 
 retcode : 0
DEBUG 2016-09-13 13:48:18,989: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 4157

 error: 
 retcode : 0
DEBUG 2016-09-13 13:48:18,989: 	 Proxy valid for 01:09:17 hours
INFO 2016-09-13 13:48:18,990: 	 Will use CRAB configuration file crab.py
DEBUG 2016-09-13 13:48:18,990: 	 Loading CRAB configuration file.
DEBUG 2016-09-13 13:48:18,994: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-09-13 13:48:18,994: 	 Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_VBF_HToZZTo4LNtuplerRunII2015_v1' already exists 
Please change the requestName in the config file
ERROR 2016-09-13 13:48:18,994: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_VBF_HToZZTo4LNtuplerRunII2015_v1' already exists 
Please change the requestName in the config file
DEBUG 2016-09-15 12:12:42,431: 	 Executing command: 'status'
DEBUG 2016-09-15 12:12:42,433: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-15 12:12:42,447: 	 Checking credentials
DEBUG 2016-09-15 12:12:42,447: 	 Proxy file /tmp/x509up_u50707 not found
DEBUG 2016-09-15 12:12:42,447: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
ERROR 2016-09-15 12:14:10,344: 	 Keyboard Interrupted
DEBUG 2016-09-16 13:37:13,960: 	 Executing command: 'status'
DEBUG 2016-09-16 13:37:13,961: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-16 13:37:14,033: 	 Checking credentials
DEBUG 2016-09-16 13:37:14,033: 	 Proxy file /tmp/x509up_u50707 not found
DEBUG 2016-09-16 13:37:14,033: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
ERROR 2016-09-16 13:57:14,078: 	 Timeout in voms-proxy-init -voms cms:/cms -valid 24:00 -rfc execution.
DEBUG 2016-09-16 13:57:14,184: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 
 error: 
Couldn't find a valid proxy.


 retcode : 1
ERROR 2016-09-16 13:57:14,184: 	 Error while checking proxy timeleft for /tmp/x509up_u50707
DEBUG 2016-09-16 13:57:14,287: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u50707 voms-proxy-info -fqan
 output : 
 error: 
Couldn't find a valid proxy.


 retcode : 1
ERROR 2016-09-16 13:57:14,287: 	 Problems creating proxy.
ERROR 2016-09-16 13:57:14,287: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-09-16 14:11:15,037: 	 Executing command: 'status'
DEBUG 2016-09-16 14:11:15,037: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-16 14:11:15,045: 	 Checking credentials
DEBUG 2016-09-16 14:11:15,046: 	 Proxy file /tmp/x509up_u50707 not found
DEBUG 2016-09-16 14:11:15,046: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-09-16 14:11:17,854: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 3
DEBUG 2016-09-16 14:11:17,957: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 
 error: 
Couldn't find a valid proxy.


 retcode : 1
ERROR 2016-09-16 14:11:17,957: 	 Error while checking proxy timeleft for /tmp/x509up_u50707
DEBUG 2016-09-16 14:11:18,060: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u50707 voms-proxy-info -fqan
 output : 
 error: 
Couldn't find a valid proxy.


 retcode : 1
ERROR 2016-09-16 14:11:18,060: 	 Problems creating proxy.
ERROR 2016-09-16 14:11:18,060: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-09-29 16:36:37,020: 	 Executing command: 'submit'
DEBUG 2016-09-29 16:36:37,021: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-29 16:36:37,042: 	 Checking credentials
DEBUG 2016-09-29 16:36:37,043: 	 Proxy file /tmp/x509up_u50707 not found
DEBUG 2016-09-29 16:36:37,043: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
ERROR 2016-09-29 16:36:39,773: 	 Keyboard Interrupted
DEBUG 2016-09-29 17:03:22,011: 	 Executing command: 'submit'
DEBUG 2016-09-29 17:03:22,012: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-29 17:03:22,018: 	 Checking credentials
DEBUG 2016-09-29 17:03:22,018: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-09-29 17:03:22,019: 	 Getting proxy life time left
DEBUG 2016-09-29 17:03:22,121: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 84927

 error: 
 retcode : 0
DEBUG 2016-09-29 17:03:22,224: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 84927

 error: 
 retcode : 0
DEBUG 2016-09-29 17:03:22,225: 	 Proxy valid for 23:35:27 hours
INFO 2016-09-29 17:03:22,225: 	 Will use CRAB configuration file crab.py
DEBUG 2016-09-29 17:03:22,225: 	 Loading CRAB configuration file.
ERROR 2016-09-29 17:03:22,244: 	 Error while loading CRAB configuration:
'Configuration' object has no attribute 'SIte'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2016-09-29 17:03:22,244: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
'Configuration' object has no attribute 'SIte'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2016-09-29 17:37:16,956: 	 Executing command: 'submit'
DEBUG 2016-09-29 17:37:16,957: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-29 17:37:16,967: 	 Checking credentials
DEBUG 2016-09-29 17:37:16,968: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-09-29 17:37:16,968: 	 Getting proxy life time left
DEBUG 2016-09-29 17:37:17,071: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 85895

 error: 
 retcode : 0
DEBUG 2016-09-29 17:37:17,173: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 85895

 error: 
 retcode : 0
DEBUG 2016-09-29 17:37:17,174: 	 Proxy valid for 23:51:35 hours
INFO 2016-09-29 17:37:17,174: 	 Will use CRAB configuration file crab.py
DEBUG 2016-09-29 17:37:17,174: 	 Loading CRAB configuration file.
DEBUG 2016-09-29 17:37:17,178: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2016-09-29 17:37:17,179: 	 Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_WW_TuneCUETP8M1_13TeV-pythia8_NtuplerRunII2015_v2' already exists 
Please change the requestName in the config file
ERROR 2016-09-29 17:37:17,179: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/zwang4/WORKSPCACE/tem/CMSSW_7_6_3/src/HiggsAnalysis/HiggsToZZ4Leptons/test/crab_projects/crab_WW_TuneCUETP8M1_13TeV-pythia8_NtuplerRunII2015_v2' already exists 
Please change the requestName in the config file
DEBUG 2016-09-29 18:06:56,815: 	 Executing command: 'submit'
DEBUG 2016-09-29 18:06:56,815: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-09-29 18:06:56,822: 	 Checking credentials
DEBUG 2016-09-29 18:06:56,823: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-09-29 18:06:56,823: 	 Getting proxy life time left
DEBUG 2016-09-29 18:06:56,925: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 84116

 error: 
 retcode : 0
DEBUG 2016-09-29 18:06:57,028: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -actimeleft
 output : 84116

 error: 
 retcode : 0
DEBUG 2016-09-29 18:06:57,028: 	 Proxy valid for 23:21:56 hours
INFO 2016-09-29 18:06:57,029: 	 Will use CRAB configuration file crab.py
DEBUG 2016-09-29 18:06:57,029: 	 Loading CRAB configuration file.
ERROR 2016-09-29 18:06:57,033: 	 Invalid CRAB configuration: Parameter Site.whitelist requires a value of type <type 'list'> (while a value of type <type 'str'> was given).
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2016-09-29 18:06:57,033: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: Parameter Site.whitelist requires a value of type <type 'list'> (while a value of type <type 'str'> was given).
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2016-10-03 16:18:41,326: 	 Executing command: 'resubmit'
DEBUG 2016-10-03 16:18:41,327: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-10-03 16:24:13,300: 	 Executing command: 'resubmit'
DEBUG 2016-10-03 16:24:13,300: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-10-03 16:24:22,998: 	 Executing command: 'resubmit'
DEBUG 2016-10-03 16:24:22,999: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-10-03 16:24:28,209: 	 Executing command: 'resubmit'
DEBUG 2016-10-03 16:24:28,210: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-10-12 01:17:35,519: 	 Executing command: 'status'
DEBUG 2016-10-12 01:17:35,520: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-10-12 01:17:35,532: 	 Checking credentials
DEBUG 2016-10-12 01:17:35,532: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-10-12 01:17:35,532: 	 Getting proxy life time left
DEBUG 2016-10-12 01:17:35,635: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2016-10-12 01:17:35,635: 	 Proxy valid for 00:00:00 hours
DEBUG 2016-10-12 01:17:35,635: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-10-12 01:17:50,667: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 3
DEBUG 2016-10-12 01:17:50,771: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2016-10-12 01:17:50,874: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u50707 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL
/cms/uscms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
ERROR 2016-10-12 01:17:50,874: 	 Problems creating proxy.
ERROR 2016-10-12 01:17:50,875: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-11-09 13:07:49,478: 	 Executing command: 'status'
DEBUG 2016-11-09 13:07:49,479: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-11-09 13:07:49,489: 	 Checking credentials
DEBUG 2016-11-09 13:07:49,489: 	 Found proxy file /tmp/x509up_u50707
DEBUG 2016-11-09 13:07:49,489: 	 Getting proxy life time left
DEBUG 2016-11-09 13:07:49,592: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2016-11-09 13:07:49,592: 	 Proxy valid for 00:00:00 hours
DEBUG 2016-11-09 13:07:49,592: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-11-09 13:09:54,045: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 3
DEBUG 2016-11-09 13:09:54,152: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 0

 error: 
 retcode : 0
DEBUG 2016-11-09 13:09:54,255: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u50707 voms-proxy-info -fqan
 output : /cms/Role=NULL/Capability=NULL
/cms/uscms/Role=NULL/Capability=NULL

 error: 
 retcode : 0
ERROR 2016-11-09 13:09:54,255: 	 Problems creating proxy.
ERROR 2016-11-09 13:09:54,255: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1608/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
DEBUG 2016-12-02 14:23:42,778: 	 Executing command: 'submit'
DEBUG 2016-12-02 14:23:42,779: 	 Found CRAB cache file /uscms/home/zwang4/.crab3
DEBUG 2016-12-02 14:23:42,791: 	 Checking credentials
DEBUG 2016-12-02 14:23:42,791: 	 Proxy file /tmp/x509up_u50707 not found
DEBUG 2016-12-02 14:23:42,791: 	 Creating new proxy for 24:00 hours with VO group '' and VO role 'NULL'.
DEBUG 2016-12-02 14:23:58,223: 	 Executing : 
 command : voms-proxy-init -voms cms:/cms -valid 24:00 -rfc
 output : None
 error: None
 retcode : 3
DEBUG 2016-12-02 14:23:58,327: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u50707 -timeleft
 output : 
 error: 
Couldn't find a valid proxy.


 retcode : 1
ERROR 2016-12-02 14:23:58,327: 	 Error while checking proxy timeleft for /tmp/x509up_u50707
DEBUG 2016-12-02 14:23:58,430: 	 Executing : 
 command : env X509_USER_PROXY=/tmp/x509up_u50707 voms-proxy-info -fqan
 output : 
 error: 
Couldn't find a valid proxy.


 retcode : 1
ERROR 2016-12-02 14:23:58,430: 	 Problems creating proxy.
ERROR 2016-12-02 14:23:58,430: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp2/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp2/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp2/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp2/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 292, in __init__
    self.proxyCreated = self.proxy.createNewVomsProxySimple(timeLeftThreshold = 720)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp2/lib/python2.7/site-packages/CRABClient/CredentialInteractions.py", line 152, in createNewVomsProxySimple
    raise ProxyCreationException("Problems creating proxy.")
ProxyCreationException: Problems creating proxy.
